import { readdir, rm } from "node:fs/promises";
import path from "node:path";
import type { ModelThinkingLevel, ThinkingLevel } from "@earendil-works/pi-ai";
import { clearDisplayResult, ephemeral, viewResult, type CommandResult } from "./commands/types.js";
import { buildHistoryItems, registerBuiltinCommands, rewindCommand } from "./commands/builtins.js";
import { parseCommandLine } from "./commands/parser.js";
import { THREAD_COMMAND_PREFIX, ThreadCommandRouter } from "./commands/registry.js";
import { CommandRegistry } from "./commands/types.js";
import { AgentLoop, DEFAULT_SYSTEM_PROMPT, type TurnResult } from "./agent/loop.js";
import type { ModelCatalog, ModelClient, ModelDescriptor } from "./agent/model-client.js";
import { ModelSemanticRunner } from "./agent/semantic-runner.js";
import { createExtensionAPI, type ExtensionAPI } from "./extensions/api.js";
import { ExtensionEvents } from "./extensions/events.js";
import { DerivedCache } from "./persistence/cache.js";
import { CapsuleService } from "./revisions/capsule-service.js";
import { MergeService } from "./revisions/merge-service.js";
import { VersionService } from "./revisions/version-service.js";
import { SessionLogStore } from "./session/log-store.js";
import { ProjectSessionCatalog } from "./session/catalog.js";
import { SessionService } from "./session/service.js";
import { registerBuiltinTools } from "./tools/builtins.js";
import { ToolRegistry } from "./tools/types.js";
import { safeUiEvent, type UiEventSink } from "./ui/events.js";
import { discoverGitWorkspace, type GitWorkspace } from "./workspace/discovery.js";
import { SidecarWorkspaceStore } from "./workspace/sidecar-store.js";
import { createId } from "./utils/id.js";

export interface ThreadAppOptions {
  rootPath: string;
  model?: ModelClient;
  modelCatalog?: ModelCatalog;
  thinkingLevel?: ModelThinkingLevel;
  systemPrompt?: string;
}

export type InputResult =
  | { kind: "command"; result: CommandResult }
  | { kind: "turn"; result: TurnResult };

interface SessionRuntime {
  log: SessionLogStore;
  session: SessionService;
  versions: VersionService;
  cache: DerivedCache;
  capsules: CapsuleService;
  merge: MergeService;
  loop: AgentLoop | undefined;
}

const THINKING_LEVELS: readonly ModelThinkingLevel[] = ["off", "minimal", "low", "medium", "high", "xhigh", "max"];
const DEFAULT_THINKING_LEVEL: ModelThinkingLevel = "medium";

/**
 * Version metacognition appended to every agent system prompt. Composed once
 * per runtime build (not per request) with this session's concrete paths, so
 * the string stays byte-stable for the lifetime of a session and prompt-cache
 * prefixes keep hitting. The agent uses this section to answer version
 * questions — including wrapped /thread diff commands — with its normal
 * atomic tools instead of a dedicated service. It also teaches the precise
 * log-query patterns (quoted type strings, batch unwrapping) and a one-call
 * reference chain so typical version questions resolve in a single tool round.
 */
function versionSystemPromptSection(log: SessionLogStore, versions: VersionService): string {
  return [
    "## Version system (thread)",
    "",
    "This project session is versioned: every durable state change is a checkpoint that pairs a full",
    "workspace snapshot with a conversation-context head. Thread commits name checkpoints as immutable",
    "milestones; branches move between checkpoints. All version data is append-only and readable with",
    "your existing tools:",
    "",
    `- Session log: ${log.eventsPath} — one JSON object per line, the canonical record of every`,
    "  message, checkpoint, branch move and commit. Query it with grep, not by reading it whole; it",
    "  grows unboundedly. Events may nest inside `batch` records",
    '  (`{"type":"batch","events":[...]}`), so unwrap matched lines with JSON parsing rather than',
    '  slicing text. Grep the quoted type string (e.g. `"type":"thread_commit_created"`): bare event',
    "  names also occur inside stored conversation messages and match falsely. Key events:",
    "  `thread_commit_created` (commit.checkpointId), `checkpoint_created` (checkpoint.id,",
    "  .parentCheckpointIds, .workspaceTreeOid, .sessionHeadId, .reason), `branch_moved` (branchName,",
    "  newCheckpointId). Refs resolve as: HEAD (current branch head), a branch name (its latest",
    "  branch_moved target), a thread commit id or prefix, or a checkpoint id or prefix.",
    `- Sidecar object store: ${versions.workspace.storeGitDir} — an independent Git object database`,
    "  holding every snapshot. Read it with git, e.g.",
    `  git --git-dir=${versions.workspace.storeGitDir} diff-tree -r <from-tree> <to-tree>.`,
    `- Context Capsules: ${path.join(log.cacheDir, "capsules", "<checkpointId>.json")} — a lossy`,
    "  summary of a checkpoint's working context, generated by /thread commit and merges. Only",
    "  committed endpoints have one; the current state never does. When a version comparison needs",
    "  context details your own memory no longer holds (for example after compaction), read the",
    "  capsule of the committed endpoint instead of guessing; treat it as a lossy cache, not a",
    "  source of truth.",
    "- The most recent `checkpoint_created` line in the log is this turn's base: a mechanical snapshot",
    "  of the workspace exactly as the current turn began. When a task asks about \"now\" or the",
    "  current state, diff against that tree instead of approximating the live workspace by hand.",
    "- A last-commit-to-now workspace diff fits in one bash call: grep the quoted",
    "  `thread_commit_created` type and read the last match commit.checkpointId; grep that id,",
    "  unwrap, and read checkpoint.workspaceTreeOid from the event that carries the `checkpoint`",
    "  object (the id also appears inside branch_moved and turn records); grep the quoted",
    "  `checkpoint_created` type and read the last match checkpoint.workspaceTreeOid — this turn's",
    "  base; then `git --git-dir=<store> diff-tree -r --stat <from-tree> <to-tree>`.",
    "",
    "Rules:",
    "- Version queries are strictly read-only. Never write to the session log or the sidecar store,",
    "  and never run git commands that create objects, refs or commits in it. Version-mutating",
    "  operations are driven by the user through /thread commands.",
    "- If the sidecar paths are outside the workspace root (linked worktrees), the read/grep/list",
    "  tools cannot reach them; use bash instead.",
  ].join("\n");
}

export class ThreadApp {
  readonly extensionApi: ExtensionAPI;
  readonly rootPath: string;
  readonly tools: ToolRegistry;
  readonly commands: CommandRegistry;
  readonly workspace: GitWorkspace;
  private runtime: SessionRuntime;
  private readonly catalog: ProjectSessionCatalog;
  private readonly events: ExtensionEvents;
  private readonly modelCatalog: ModelCatalog | undefined;
  private readonly systemPrompt: string | undefined;
  private readonly commandRouter: ThreadCommandRouter;
  private currentModel: ModelClient | undefined;
  private preferredThinkingLevel: ModelThinkingLevel;
  private currentThinkingLevel: ModelThinkingLevel = "off";
  private activeInputCount = 0;
  private sessionTransitioning = false;

  private constructor(
    options: ThreadAppOptions,
    workspace: GitWorkspace,
    catalog: ProjectSessionCatalog,
    log: SessionLogStore,
    session: SessionService,
    versions: VersionService,
  ) {
    this.rootPath = workspace.rootPath;
    this.workspace = workspace;
    this.catalog = catalog;
    this.events = new ExtensionEvents();
    this.modelCatalog = options.modelCatalog;
    this.systemPrompt = options.systemPrompt;
    this.tools = new ToolRegistry();
    registerBuiltinTools(this.tools);
    this.commands = new CommandRegistry();
    registerBuiltinCommands(this.commands);
    this.commandRouter = new ThreadCommandRouter(this.commands);
    this.extensionApi = createExtensionAPI(this.tools, this.commands, this.events);
    this.preferredThinkingLevel = options.thinkingLevel ?? DEFAULT_THINKING_LEVEL;
    this.currentModel = options.model;
    this.currentThinkingLevel = this.clampThinkingLevel(options.model, this.preferredThinkingLevel);
    this.runtime = this.buildRuntime(log, session, versions);
  }

  static async open(options: ThreadAppOptions): Promise<ThreadApp> {
    const workspace = await discoverGitWorkspace(path.resolve(options.rootPath));
    const catalog = await ProjectSessionCatalog.open({
      rootPath: workspace.rootPath,
      sidecarRoot: workspace.sidecarRoot,
    });
    let log: SessionLogStore | undefined;
    try {
      const sessionId = catalog.activeSessionId;
      const registered = catalog.list().some((session) => session.id === sessionId);
      log = await SessionLogStore.open({
        rootPath: workspace.rootPath,
        sidecarRoot: workspace.sidecarRoot,
        sessionId,
      });
      const session = new SessionService(log);
      const sidecar = new SidecarWorkspaceStore({ workspace, sessionId: log.sessionId });
      const versions = new VersionService(session, sidecar);
      await versions.initialize(workspace.rootPath, { active: true, create: !registered });
      await catalog.activate(log.sessionId, session.projection.session!.createdAt);
      return new ThreadApp(options, workspace, catalog, log, session, versions);
    } catch (error) {
      await log?.close();
      await catalog.close();
      throw error;
    }
  }

  get session(): SessionService {
    return this.runtime.session;
  }

  get versions(): VersionService {
    return this.runtime.versions;
  }

  get capsules(): CapsuleService {
    return this.runtime.capsules;
  }

  get merge(): MergeService {
    return this.runtime.merge;
  }

  private get loop(): AgentLoop | undefined {
    return this.runtime.loop;
  }

  get model(): ModelClient | undefined {
    return this.currentModel;
  }

  get thinkingLevel(): ModelThinkingLevel {
    return this.currentThinkingLevel;
  }

  get supportsThinking(): boolean {
    return this.currentModel?.reasoning === true;
  }

  get availableThinkingLevels(): readonly ModelThinkingLevel[] {
    return this.thinkingLevelsFor(this.currentModel);
  }

  cycleThinkingLevel(): ModelThinkingLevel | undefined {
    if (!this.currentModel?.reasoning) return undefined;
    const levels = this.thinkingLevelsFor(this.currentModel);
    const currentIndex = levels.indexOf(this.currentThinkingLevel);
    this.preferredThinkingLevel = levels[(currentIndex + 1) % levels.length]!;
    this.configureRuntime(this.currentModel);
    return this.currentThinkingLevel;
  }

  private thinkingLevelsFor(model: ModelClient | undefined): readonly ModelThinkingLevel[] {
    if (!model?.reasoning) return ["off"];
    const levels = model.supportedThinkingLevels?.filter((level, index, values) => values.indexOf(level) === index);
    return levels && levels.length > 0 ? levels : ["off", "minimal", "low", "medium", "high"];
  }

  private clampThinkingLevel(model: ModelClient | undefined, requested: ModelThinkingLevel): ModelThinkingLevel {
    const available = this.thinkingLevelsFor(model);
    if (available.includes(requested)) return requested;
    const requestedIndex = THINKING_LEVELS.indexOf(requested);
    for (let index = requestedIndex; index < THINKING_LEVELS.length; index++) {
      const candidate = THINKING_LEVELS[index]!;
      if (available.includes(candidate)) return candidate;
    }
    for (let index = requestedIndex - 1; index >= 0; index--) {
      const candidate = THINKING_LEVELS[index]!;
      if (available.includes(candidate)) return candidate;
    }
    return available[0] ?? "off";
  }

  private requestReasoning(): ThinkingLevel | undefined {
    return this.currentThinkingLevel === "off" ? undefined : this.currentThinkingLevel;
  }

  private configureRuntime(model: ModelClient | undefined): void {
    this.currentModel = model;
    this.currentThinkingLevel = this.clampThinkingLevel(model, this.preferredThinkingLevel);
    this.runtime = this.buildRuntime(this.runtime.log, this.runtime.session, this.runtime.versions);
  }

  private buildRuntime(
    log: SessionLogStore,
    session: SessionService,
    versions: VersionService,
  ): SessionRuntime {
    const cache = new DerivedCache(log.cacheDir);
    const reasoning = this.requestReasoning();
    const semantic = this.currentModel ? new ModelSemanticRunner(this.currentModel, reasoning) : undefined;
    const capsules = new CapsuleService(session, cache, semantic);
    const merge = new MergeService(versions, session, capsules, semantic);
    const systemPrompt = `${this.systemPrompt ?? DEFAULT_SYSTEM_PROMPT}\n\n${versionSystemPromptSection(log, versions)}`;
    const loop = this.currentModel
      ? new AgentLoop(
          this.rootPath,
          this.currentModel,
          session,
          versions,
          this.tools,
          this.events,
          {
            systemPrompt,
            ...(reasoning ? { reasoning } : {}),
          },
        )
      : undefined;
    return { log, session, versions, cache, capsules, merge, loop };
  }

  private async openSessionRuntime(
    sessionId: string,
    options: { active: boolean; create: boolean },
  ): Promise<SessionRuntime> {
    const log = await SessionLogStore.open({
      rootPath: this.rootPath,
      sidecarRoot: this.workspace.sidecarRoot,
      sessionId,
    });
    try {
      const session = new SessionService(log);
      const sidecar = new SidecarWorkspaceStore({ workspace: this.workspace, sessionId });
      const versions = new VersionService(session, sidecar);
      await versions.initialize(this.rootPath, options);
      return this.buildRuntime(log, session, versions);
    } catch (error) {
      await log.close();
      if (options.create) {
        await new SidecarWorkspaceStore({ workspace: this.workspace, sessionId }).deleteSessionObjects()
          .catch(() => undefined);
        await rm(log.sessionDir, { recursive: true, force: true }).catch(() => undefined);
      }
      throw error;
    }
  }

  private sessionListResult(): CommandResult {
    const sessions = this.catalog.list();
    const content = sessions.map((session) =>
      `${session.current ? "*" : " "} ${session.id}  created ${new Date(session.createdAt).toISOString()}  last used ${new Date(session.lastActivatedAt).toISOString()}`
    ).join("\n");
    return viewResult(content || "(no project sessions)", { type: "session_picker", sessions });
  }

  private async createProjectSession(signal: AbortSignal): Promise<string> {
    signal.throwIfAborted();
    this.versions.requireIdle();
    const previous = this.runtime;
    await previous.versions.syncCurrentWorkspace("safety", true);
    signal.throwIfAborted();
    const sessionId = createId("session");
    let next: SessionRuntime | undefined;
    try {
      next = await this.openSessionRuntime(sessionId, { active: false, create: true });
      signal.throwIfAborted();
      await this.catalog.activate(sessionId, next.session.projection.session!.createdAt);
    } catch (error) {
      if (next) {
        await next.log.close();
        await next.versions.workspace.deleteSessionObjects().catch(() => undefined);
        await rm(next.log.sessionDir, { recursive: true, force: true }).catch(() => undefined);
      }
      throw error;
    }
    this.runtime = next;
    await previous.log.close();
    return sessionId;
  }

  private async switchProjectSession(idOrPrefix: string, signal: AbortSignal): Promise<string | undefined> {
    signal.throwIfAborted();
    const sessionId = this.catalog.resolve(idOrPrefix);
    if (sessionId === this.runtime.log.sessionId) return undefined;
    this.versions.requireIdle();
    const previous = this.runtime;
    const safety = await previous.versions.syncCurrentWorkspace("safety", true);
    signal.throwIfAborted();
    const next = await this.openSessionRuntime(sessionId, { active: false, create: false });
    let restored = false;
    try {
      await next.versions.workspace.restoreTree(safety.workspaceTreeOid, next.versions.head.workspaceTreeOid);
      restored = true;
      signal.throwIfAborted();
      await this.catalog.activate(sessionId, next.session.projection.session!.createdAt);
    } catch (error) {
      if (restored) {
        await next.versions.workspace.restoreTree(next.versions.head.workspaceTreeOid, safety.workspaceTreeOid)
          .catch(() => undefined);
      }
      await next.log.close();
      throw error;
    }
    this.runtime = next;
    await previous.log.close();
    return sessionId;
  }

  private modelPickerModels(scope: "configured" | "all"): ModelDescriptor[] {
    if (!this.modelCatalog) return [];
    const models = scope === "all"
      ? (this.modelCatalog.listAll?.() ?? this.modelCatalog.list())
      : this.modelCatalog.list();
    const current = this.currentModel;
    if (!current || models.some((model) =>
      model.providerId === current.providerId && model.modelId === current.modelId
    )) return models;
    const descriptor = (this.modelCatalog.listAll?.(current.providerId) ?? this.modelCatalog.list(current.providerId))
      .find((model) => model.providerId === current.providerId && model.modelId === current.modelId) ?? {
        providerId: current.providerId,
        modelId: current.modelId,
        name: current.modelId,
        contextWindow: current.contextWindow,
        maxOutputTokens: current.maxOutputTokens,
        reasoning: current.reasoning ?? false,
      };
    return [...models, descriptor].sort((left, right) =>
      left.providerId.localeCompare(right.providerId) || left.modelId.localeCompare(right.modelId),
    );
  }

  private modelStatus(scope: "configured" | "all" = "configured"): CommandResult {
    const models = this.modelPickerModels(scope);
    const scopeLine = scope === "all"
      ? `Complete catalog: ${models.length.toLocaleString("en-US")} model(s).`
      : `Configured/current choices: ${models.length.toLocaleString("en-US")} model(s). Use /model all for the complete catalog.`;
    const content = this.currentModel
      ? [
        `Current model: ${this.currentModel.providerId}/${this.currentModel.modelId}`,
        `Context window: ${this.currentModel.contextWindow.toLocaleString("en-US")} tokens`,
        `Maximum output: ${this.currentModel.maxOutputTokens.toLocaleString("en-US")} tokens`,
        ...(this.supportsThinking
          ? [`Thinking level: ${this.currentThinkingLevel} (Shift+Tab to cycle)`]
          : []),
        scopeLine,
        "Use /model list [provider] or /model <provider>/<model> to switch.",
      ].join("\n")
      : [
        "No model selected.",
        scopeLine,
        "Use /model list [provider] and /model <provider>/<model> to select one.",
      ].join("\n");
    if (!this.modelCatalog) return ephemeral(content);
    return viewResult(content, {
      type: "model_picker",
      models,
      currentProviderId: this.currentModel?.providerId,
      currentModelId: this.currentModel?.modelId,
      scope,
    });
  }

  private modelList(providerId?: string): CommandResult {
    if (!this.modelCatalog) {
      throw new Error("Model listing is unavailable because this application was opened without a model catalog");
    }
    const models = providerId
      ? (this.modelCatalog.listAll?.(providerId) ?? this.modelCatalog.list(providerId))
      : this.modelPickerModels("configured");
    if (models.length === 0) {
      throw new Error(
        providerId
          ? `No models found for provider ${providerId}`
          : "No configured models are available. Use /model all to browse the complete catalog.",
      );
    }
    return ephemeral([
      `${providerId ? `Available models for ${providerId}` : "Configured/current models"} (${models.length}):`,
      ...models.map((model) => this.formatModel(model)),
    ].join("\n"));
  }

  private formatModel(model: ModelDescriptor): string {
    const current = this.currentModel?.providerId === model.providerId && this.currentModel.modelId === model.modelId;
    const detail = [
      model.name !== model.modelId ? model.name : undefined,
      `${model.contextWindow.toLocaleString("en-US")} context`,
      model.reasoning ? "reasoning" : undefined,
    ].filter((value): value is string => value !== undefined).join(", ");
    return `${current ? "*" : " "} ${model.providerId}/${model.modelId} — ${detail}`;
  }

  private handleModelCommand(args: string[]): CommandResult {
    if (args.length === 0) return this.modelStatus();
    if (args[0] === "all") {
      if (args.length !== 1) throw new Error("Usage: /model all");
      if (!this.modelCatalog) {
        throw new Error("Full model listing is unavailable because this application was opened without a model catalog");
      }
      return this.modelStatus("all");
    }
    if (args[0] === "list") {
      if (args.length > 2) throw new Error("Usage: /model list [provider]");
      return this.modelList(args[1]);
    }
    let providerId: string;
    let modelId: string;
    if (args.length === 1) {
      const separator = args[0]!.indexOf("/");
      if (separator <= 0 || separator === args[0]!.length - 1) {
        throw new Error("Usage: /model <provider>/<model> or /model <provider> <model>");
      }
      providerId = args[0]!.slice(0, separator);
      modelId = args[0]!.slice(separator + 1);
    } else if (args.length === 2) {
      [providerId, modelId] = args as [string, string];
    } else {
      throw new Error("Usage: /model <provider>/<model> or /model <provider> <model>");
    }
    if (this.currentModel?.providerId === providerId && this.currentModel.modelId === modelId) {
      return ephemeral(`Already using ${providerId}/${modelId}`);
    }
    if (!this.modelCatalog) {
      throw new Error("Model switching is unavailable because this application was opened without a model catalog");
    }
    const previous = this.currentModel
      ? `${this.currentModel.providerId}/${this.currentModel.modelId}`
      : "no model";
    const selected = this.modelCatalog.createClient(providerId, modelId);
    this.configureRuntime(selected);
    return ephemeral(`Switched model from ${previous} to ${providerId}/${modelId}`, true);
  }

  async handleInput(
    input: string,
    options: { signal: AbortSignal; onTextDelta?: (delta: string) => void; onUiEvent?: UiEventSink },
  ): Promise<InputResult> {
    const trimmed = input.trim();
    const transition = trimmed === "/new" || /^\/session\s+switch(?:\s|$)/.test(trimmed);
    if (this.sessionTransitioning) throw new Error("A project session transition is already running");
    if (transition && this.activeInputCount > 0) {
      throw new Error("Wait for the active turn or command before changing project sessions");
    }
    this.activeInputCount++;
    if (transition) this.sessionTransitioning = true;
    try {
      return await this.handleInputInner(input, options);
    } finally {
      this.activeInputCount--;
      if (transition) this.sessionTransitioning = false;
    }
  }

  private async handleInputInner(
    input: string,
    options: { signal: AbortSignal; onTextDelta?: (delta: string) => void; onUiEvent?: UiEventSink },
  ): Promise<InputResult> {
    const isNewCommand = input === "/new" || (input.startsWith("/new") && /\s/.test(input[4] ?? ""));
    if (isNewCommand) {
      if (input.trim() !== "/new") throw new Error("Usage: /new");
      safeUiEvent(options.onUiEvent, { type: "command_started", name: "new" });
      try {
        const sessionId = await this.createProjectSession(options.signal);
        safeUiEvent(options.onUiEvent, {
          type: "session_changed",
          sessionId,
          branch: this.versions.currentBranch.name,
          checkpointId: this.versions.head.id,
          reason: "new",
        });
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "new", ok: true });
        return {
          kind: "command",
          result: ephemeral(`Started new project session ${sessionId} from the current workspace`, true),
        };
      } catch (error) {
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "new", ok: false });
        throw error;
      }
    }
    const sessionPrefix = "/session";
    const isSessionCommand = input === sessionPrefix ||
      (input.startsWith(sessionPrefix) && /\s/.test(input[sessionPrefix.length] ?? ""));
    if (isSessionCommand) {
      safeUiEvent(options.onUiEvent, { type: "command_started", name: "session" });
      try {
        options.signal.throwIfAborted();
        const args = parseCommandLine(input.slice(sessionPrefix.length).trim());
        if (args.length === 0 || (args.length === 1 && args[0] === "list")) {
          const result = this.sessionListResult();
          safeUiEvent(options.onUiEvent, { type: "command_finished", name: "session", ok: true });
          return { kind: "command", result };
        }
        if (args[0] !== "switch" || args.length !== 2) {
          throw new Error("Usage: /session [list] or /session switch <session-id-or-prefix>");
        }
        const sessionId = await this.switchProjectSession(args[1]!, options.signal);
        if (sessionId) {
          safeUiEvent(options.onUiEvent, {
            type: "session_changed",
            sessionId,
            branch: this.versions.currentBranch.name,
            checkpointId: this.versions.head.id,
            reason: "switch",
          });
        }
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "session", ok: true });
        return {
          kind: "command",
          result: sessionId
            ? ephemeral(`Switched to project session ${sessionId}`, true)
            : ephemeral(`Already using project session ${this.runtime.log.sessionId}`),
        };
      } catch (error) {
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "session", ok: false });
        throw error;
      }
    }
    const commandContext = {
      rootPath: this.rootPath,
      versions: this.versions,
      merge: this.merge,
      capsules: this.capsules,
      signal: options.signal,
    };
    const isClearCommand = input === "/clear" || (input.startsWith("/clear") && /\s/.test(input[6] ?? ""));
    if (isClearCommand) {
      if (input.trim() !== "/clear") throw new Error("Usage: /clear");
      safeUiEvent(options.onUiEvent, { type: "command_started", name: "clear" });
      safeUiEvent(options.onUiEvent, { type: "command_finished", name: "clear", ok: true });
      return { kind: "command", result: clearDisplayResult() };
    }
    const isModelCommand = input === "/model" || (input.startsWith("/model") && /\s/.test(input[6] ?? ""));
    if (isModelCommand) {
      safeUiEvent(options.onUiEvent, { type: "command_started", name: "model" });
      try {
        options.signal.throwIfAborted();
        const result = this.handleModelCommand(parseCommandLine(input.slice(6).trim()));
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "model", ok: true });
        return { kind: "command", result };
      } catch (error) {
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "model", ok: false });
        throw error;
      }
    }
    const isCompactCommand = input === "/compact" || (input.startsWith("/compact") && /\s/.test(input[8] ?? ""));
    if (isCompactCommand) {
      if (input.trim() !== "/compact") throw new Error("Usage: /compact");
      if (!this.loop) throw new Error("/compact requires a configured model");
      safeUiEvent(options.onUiEvent, { type: "command_started", name: "compact" });
      try {
        const compacted = await this.loop.compactCurrent({
          signal: options.signal,
          ...(options.onUiEvent ? { onUiEvent: options.onUiEvent } : {}),
        });
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "compact", ok: true });
        if (!compacted.compacted) {
          return {
            kind: "command",
            result: ephemeral("Nothing to compact; the current context only contains the retained interaction tail"),
          };
        }
        safeUiEvent(options.onUiEvent, {
          type: "head_changed",
          branch: this.versions.currentBranch.name,
          checkpointId: compacted.checkpointId!,
          reason: "command",
        });
        return {
          kind: "command",
          result: ephemeral(
            `Context compacted: ${compacted.summarizedMessages} message(s) summarized, ${compacted.retainedMessages} message(s) retained, ${compacted.modelCalls} model call(s); checkpoint ${compacted.checkpointId}`,
            true,
          ),
        };
      } catch (error) {
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "compact", ok: false });
        throw error;
      }
    }
    /* /thread diff is captured here and re-issued to the agent as a wrapped
     * user message instead of routing to a dedicated diff service: the agent
     * reads the version data itself with its atomic tools (see the version
     * section of its system prompt) and its reply is an ordinary append-only
     * turn. Persisting the wrapped prompt — not the bare command — keeps the
     * canonical log faithful to what the model actually saw. */
    const isThreadDiffCommand = input === "/thread diff" ||
      (input.startsWith("/thread diff") && /\s/.test(input["/thread diff".length] ?? ""));
    if (isThreadDiffCommand) {
      const args = parseCommandLine(input.slice("/thread diff".length).trim());
      const factsOnly = args.includes("--facts");
      const refs = args.filter((arg) => arg !== "--facts");
      if (refs.length !== 0 && refs.length !== 2) {
        throw new Error("Usage: /thread diff [<from> <to>] [--facts]");
      }
      if (!this.loop) {
        throw new Error("/thread diff runs as an agent turn, which requires a configured model");
      }
      const command = `/thread diff${refs.length > 0 ? ` ${refs.join(" ")}` : ""}${factsOnly ? " --facts" : ""}`;
      const prompt = [
        "The user ran the slash command:",
        "",
        `    ${command}`,
        "",
        ...(refs.length === 0
          ? [
            "Compare the most recent thread commit with the current state of this session.",
            "Workspace: resolve the most recent thread commit and this turn's base checkpoint (the",
            "latest checkpoint_created event), then diff their workspace trees through the sidecar",
            "object store.",
            "Context: summarize how the working context evolved since that commit, from your own",
            "memory of this session.",
          ]
          : [
            `Compare thread version ${refs[0]} with thread version ${refs[1]}.`,
            "Resolve both refs yourself (branch name, thread commit id or prefix, or checkpoint id or",
            "prefix), diff their workspace trees through the sidecar object store, and compare their",
            "context heads by reading the session log.",
          ]),
        ...(factsOnly
          ? [
            "Report only deterministic facts — changed files with statuses and line counts, and which",
            "entries lie between the two context heads. Do not interpret or speculate.",
          ]
          : ["Keep mechanical facts separate from your interpretation."]),
      ].join("\n");
      return {
        kind: "turn",
        result: await this.loop.run(prompt, {
          signal: options.signal,
          ...(options.onTextDelta ? { onTextDelta: options.onTextDelta } : {}),
          ...(options.onUiEvent ? { onUiEvent: options.onUiEvent } : {}),
        }),
      };
    }
    const prefixLength = THREAD_COMMAND_PREFIX.length;
    const isThreadCommand = input === THREAD_COMMAND_PREFIX ||
      (input.startsWith(THREAD_COMMAND_PREFIX) && /\s/.test(input[prefixLength] ?? ""));
    if (isThreadCommand) {
      const name = parseCommandLine(input.slice(prefixLength).trim())[0] ?? "help";
      const beforeBranch = this.versions.currentBranch.name;
      const beforeHead = this.versions.head.id;
      safeUiEvent(options.onUiEvent, { type: "command_started", name });
      try {
        const command = await this.commandRouter.route(input, commandContext);
        if (!command) throw new Error(`Could not route command: ${input}`);
        safeUiEvent(options.onUiEvent, { type: "command_finished", name, ok: true });
        if (beforeBranch !== this.versions.currentBranch.name || beforeHead !== this.versions.head.id) {
          safeUiEvent(options.onUiEvent, {
            type: "head_changed",
            branch: this.versions.currentBranch.name,
            checkpointId: this.versions.head.id,
            reason: "command",
          });
        }
        return { kind: "command", result: command };
      } catch (error) {
        safeUiEvent(options.onUiEvent, { type: "command_finished", name, ok: false });
        throw error;
      }
    }
    if (input.startsWith("/rewind") && (input.length === 7 || /\s/.test(input[7]!))) {
      const args = parseCommandLine(input.slice(7).trim());
      if (args.length > 1) throw new Error("Usage: /rewind [turn-id-or-user-entry-id]");
      if (args.length === 0) {
        // No id given: open the rewind picker over the session, one row per
        // user message, and let the user choose how far back to go.
        safeUiEvent(options.onUiEvent, { type: "command_started", name: "rewind" });
        const items = buildHistoryItems(commandContext);
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "rewind", ok: true });
        if (items.length === 0) {
          return {
            kind: "command",
            result: ephemeral(`(no turns on thread branch ${this.versions.currentBranch.name})`),
          };
        }
        return {
          kind: "command",
          result: viewResult("Choose a user message to rewind to.", { type: "rewind", items }),
        };
      }
      safeUiEvent(options.onUiEvent, { type: "command_started", name: "rewind" });
      try {
        const result = await rewindCommand(args[0]!, commandContext);
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "rewind", ok: true });
        safeUiEvent(options.onUiEvent, {
          type: "head_changed",
          branch: this.versions.currentBranch.name,
          checkpointId: this.versions.head.id,
          reason: "restore",
        });
        return { kind: "command", result };
      } catch (error) {
        safeUiEvent(options.onUiEvent, { type: "command_finished", name: "rewind", ok: false });
        throw error;
      }
    }
    if (!this.loop) {
      throw new Error(
        "No model configured. Use /model list and /model <provider>/<model>, configure a default, or set --provider/--model.",
      );
    }
    return {
      kind: "turn",
      result: await this.loop.run(input, {
        signal: options.signal,
        ...(options.onTextDelta ? { onTextDelta: options.onTextDelta } : {}),
        ...(options.onUiEvent ? { onUiEvent: options.onUiEvent } : {}),
      }),
    };
  }

  async fsck(): Promise<string[]> {
    const summaries = this.catalog.list();
    const existingIds = new Set<string>();
    const issues: string[] = [];
    const sessionsRoot = path.join(this.workspace.sidecarRoot, "sessions");
    for (const entry of await readdir(sessionsRoot, { withFileTypes: true }).catch(() => [])) {
      if (entry.isDirectory() && /^session_[A-Za-z0-9]+$/.test(entry.name)) existingIds.add(entry.name);
    }
    issues.push(...await this.catalog.fsck(existingIds));
    const registeredIds = new Set(summaries.map((summary) => summary.id));
    for (const id of existingIds) {
      if (!registeredIds.has(id)) issues.push(`session directory is not registered in the catalog: ${id}`);
    }
    if (this.catalog.activeSessionId !== this.runtime.log.sessionId) {
      issues.push(
        `session catalog active id is ${this.catalog.activeSessionId}; open session is ${this.runtime.log.sessionId}`,
      );
    }
    issues.push(...await this.fsckRuntime(this.runtime));
    for (const summary of summaries) {
      if (summary.current || !existingIds.has(summary.id)) continue;
      let log: SessionLogStore | undefined;
      try {
        log = await SessionLogStore.open({
          rootPath: this.rootPath,
          sidecarRoot: this.workspace.sidecarRoot,
          sessionId: summary.id,
        });
        const session = new SessionService(log);
        const versions = new VersionService(
          session,
          new SidecarWorkspaceStore({ workspace: this.workspace, sessionId: summary.id }),
        );
        issues.push(...(await this.fsckRuntime(this.buildRuntime(log, session, versions)))
          .map((issue) => `${summary.id}: ${issue}`));
      } catch (error) {
        issues.push(`${summary.id}: ${error instanceof Error ? error.message : String(error)}`);
      } finally {
        await log?.close();
      }
    }
    return issues;
  }

  private async fsckRuntime(runtime: SessionRuntime): Promise<string[]> {
    const issues: string[] = [];
    for (const branch of runtime.session.projection.branches.values()) {
      if (!runtime.session.projection.checkpoints.has(branch.headCheckpointId)) {
        issues.push(`branch ${branch.name} references missing checkpoint ${branch.headCheckpointId}`);
      }
    }
    for (const commit of runtime.session.projection.commits.values()) {
      if (!runtime.session.projection.checkpoints.has(commit.checkpointId)) {
        issues.push(`commit ${commit.id} references missing checkpoint ${commit.checkpointId}`);
      }
    }
    for (const checkpoint of runtime.session.projection.checkpoints.values()) {
      try {
        await runtime.versions.workspace.verifySnapshot(checkpoint.workspaceTreeOid, checkpoint.retentionCommitOid);
      } catch (error) {
        issues.push(`checkpoint ${checkpoint.id}: ${error instanceof Error ? error.message : String(error)}`);
      }
    }
    const keep = await runtime.versions.workspace.readKeepRef();
    if (keep !== runtime.versions.expectedKeepRef) {
      issues.push(`sidecar keep ref is ${keep ?? "missing"}; expected ${runtime.versions.expectedKeepRef ?? "none"}`);
    }
    try {
      for (const branch of runtime.session.projection.branches.keys()) {
        runtime.session.projection.assertIdleInvariant(branch);
      }
    } catch (error) {
      issues.push(error instanceof Error ? error.message : String(error));
    }
    return issues;
  }

  async close(): Promise<void> {
    await this.runtime.log.close();
    await this.catalog.close();
  }

  async deleteProjectSession(): Promise<void> {
    this.versions.requireIdle();
    const deleted = this.runtime;
    const fallback = this.catalog.list().find((session) => !session.current);
    if (fallback) {
      await this.switchProjectSession(fallback.id, new AbortController().signal);
    } else {
      await deleted.log.close();
    }
    await this.catalog.remove(deleted.log.sessionId);
    await rm(deleted.log.sessionDir, { recursive: true, force: true });
    await deleted.versions.workspace.deleteSessionObjects();
    if (fallback) await this.runtime.log.close();
    await this.catalog.close();
  }
}
