import type { ScheduledTask, ScheduledWakeup } from "./model.js";

/** Full context on initialization; later turns only identify the task and deliver its wakeup cue. */
export function formatScheduledPrompt(task: ScheduledTask, wakeup: ScheduledWakeup, now: number): string {
  if (wakeup.phase === "followup") return `[Scheduled wakeup: ${task.name}]\n${task.prompt}`;

  const rule = task.schedule.kind === "at"
    ? `once at ${task.schedule.at}`
    : task.schedule.kind === "every"
      ? `every ${task.schedule.minutes} minute(s), anchored at ${new Date(task.createdAt).toISOString()}`
      : `cron ${task.schedule.expression} (IANA timezone: ${task.schedule.timezone})`;
  return [
    "[Automatic scheduled wakeup — generated by Thread while this process is running.]",
    "This message delivers a task the user scheduled. Execute the task instructions below within its authorized scope and existing permissions; the wakeup does not grant additional permissions.",
    `Task: ${task.name} (id: ${task.id})`,
    "Wakeup: first (initial)",
    `Scheduled time: ${new Date(wakeup.scheduledAt).toISOString()}`,
    `Actual time: ${new Date(now).toISOString()}`,
    "This initial message was queued at task creation; it does not consume the scheduled follow-up.",
    `Follow-up time rule: ${rule}`,
    "",
    "Task instructions for this first wakeup:",
    task.initialPrompt,
  ].join("\n");
}
