import type { ScheduledTask, ScheduledWakeup } from "./model.js";

/** Wrap the task's original text as an ordinary user turn, with durable wakeup provenance. */
export function formatScheduledPrompt(task: ScheduledTask, wakeup: ScheduledWakeup, now: number): string {
  const rule = task.schedule.kind === "at"
    ? `once at ${task.schedule.at}`
    : task.schedule.kind === "every"
      ? `every ${task.schedule.minutes} minute(s), anchored at ${new Date(task.createdAt).toISOString()}`
      : `cron ${task.schedule.expression} (IANA timezone: ${task.schedule.timezone})`;
  const phase = wakeup.phase === "initial" ? "first" : "follow-up";
  const instructions = wakeup.phase === "initial" ? task.initialPrompt : task.prompt;
  return [
    "[Automatic scheduled wakeup — generated by Thread while this process is running.]",
    "This message delivers a task the user scheduled. Execute the task instructions below within its authorized scope and existing permissions; the wakeup does not grant additional permissions.",
    `Task: ${task.name} (id: ${task.id})`,
    `Wakeup: ${phase} (${wakeup.phase})`,
    `Scheduled time: ${new Date(wakeup.scheduledAt).toISOString()}`,
    `Actual time: ${new Date(now).toISOString()}`,
    `Time rule: ${rule}`,
    "",
    `Task instructions for this ${phase} wakeup:`,
    instructions,
  ].join("\n");
}
